### PR TITLE
#16 handle undefined item code

### LINKED ISSUE #16: No itemCode provided just selects some item instead of error
If you make a request with an undefined (perhaps for null too?) `itemCode` then OMS gets some item back (maybe first of all items unordered?) and the plugin uses that. The plugin should reject the request and rollback any records created.

Example:

Input failing to specify itemCode parameter
```JSON
{
  "input": {
    "invoiceId": "e93192b3-3e9c-46ea-85e5-eeafc228fbd5",
    "customerCode": "GP", 
    "items": [
      {
        "whoopsWrongKeyForSpecifyingItemCode!": "RX01032",
        "numberOfUnits": 10
      }
    ]
  }
}
```

Success on `"Inserted itemCode: undefined..."`???:
```JSON
{
  "data": {
    "pluginGraphqlQuery": {
      "items": [
        {
          "message": "Inserted itemCode: undefined, Number of units requested: 1, Allocated Units: 1, Placeholder Units: 0",
          "success": true
        }
      ],
      "message": "Issued stock from store code: GEN, for customer: General Patient, invoiceId: e93192b3-3e9c-46ea-85e5-eeafc228fbd9, items given count: 1, aggregated items count: 1.",
      "success": true
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Chris-Petty**
fixes #16 

Claude a guard against itemCode being undefined

An alternative might have been doing some JSON schema with zod or something, but this is fine for now. My dream would be actual gql API with some more built in validation from rust side but maybe asking too much there

### CODE REVIEW

File: backend/latest/src/plugin.ts [hunk 1]
```diff
@@ -103,6 +103,22 @@ const plugins: BackendPlugins = {
...
+        item.itemCode.trim() === ''
+      ) {
+        itemsResponses.push({
+          itemCode: item.itemCode,
+          success: false,
+          message: "param 'itemCode' is empty or invalid",
+        });
+        updateToShipped = false;
+        rollbackOperation = true;
+        continue;
```
Comment (guatemartin) [inline backend/latest/src/plugin.ts:119]: It's been a minute since I looked at this, but I guess we "continue" so we iterate through all items to return a list of errors?  Otherwise we would just "break;" right?  If that's the case, just ignore comment.

**Review by guatemartin — APPROVED** [review]
LGTM.  I put a comment there in the code, but I'm pretty sure it's a "MOO" point :).

File: backend/latest/src/plugin.ts (hunk 1 above)
Comment (Chris-Petty) [reply backend/latest/src/plugin.ts:119]: Yea it'll build a list of errors which seems ideal to me
